Repository AY2425S2-CS2113-F12-3/tp, pull requests merged in 2025-03, with the labels that each got.

#17 Branch for solve command
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/Command.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/common/Messages.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/parser/Parser.java
Labels: type.Story, priority.High

#19 Adds ListCommand and CommandResult class
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/Command.java
  src/main/java/mindexpander/commands/CommandResult.java
  src/main/java/mindexpander/commands/ListCommand.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/common/Messages.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/parser/Parser.java
  src/main/java/mindexpander/ui/TextUi.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#36 Branch help Junit test
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/commands/ListCommand.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
Labels: type.Task, priority.High

#37 Improve the solve command
  docs/UserGuide.md
  src/main/java/mindexpander/commands/Command.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/commands/SolveCommandOneStep.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/SolveCommandOneStepTest.java
  src/test/java/mindexpander/tests/SolveCommandTest.java
Labels: type.Enhancement, priority.Medium

#48 Junit test for addCommand
  META-INF/MANIFEST.MF
  build.gradle
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/data/question/Question.java
  src/main/java/mindexpander/parser/Parser.java
  src/main/java/mindexpander/storage/StorageFile.java
  src/test/java/mindexpander/tests/AddCommandTest.java
Labels: type.Task, priority.Medium

#46 Implement Find Command and Last Shown List
  build.gradle
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/CommandResult.java
  src/main/java/mindexpander/commands/FindCommand.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/commands/ListCommand.java
  src/main/java/mindexpander/common/Messages.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/data/question/FillInTheBlanks.java
  src/main/java/mindexpander/data/question/Question.java
  src/main/java/mindexpander/parser/Parser.java
  src/main/java/mindexpander/ui/TextUi.java
  src/test/java/mindexpander/tests/FindCommandTest.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  src/test/java/mindexpander/tests/ListCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, priority.Medium
