Repository AY2425S2-CS2113-F12-3/tp, pull requests merged in 2025-04, with the labels that each got.

#52 Branch improve help
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/Command.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/commands/SolveCommandOneStep.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/expectedloader.bat
  text-ui-test/input.txt
Labels: type.Enhancement, priority.Medium

#57 Branch reformat solve
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/class/CommandHandling.png
  docs/diagrams/class/CommandHandling.puml
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/commands/SolveCommandOneStep.java
  src/main/java/mindexpander/data/question/Question.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  src/test/java/mindexpander/tests/SolveCommandOneStepTest.java
  src/test/java/mindexpander/tests/SolveCommandTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, priority.High

#61 Branch documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/pics/xuyan.jpg
  docs/team/liuxuyan.md
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/EditCommand.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/test/java/mindexpander/tests/AddCommandTest.java
  src/test/java/mindexpander/tests/EditCommandTest.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
Labels: type.Task

#63 Updates guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/class/CommandHandling.png
  docs/diagrams/class/CommandHandling.puml
  docs/diagrams/class/DataDiagram.png
  docs/diagrams/class/DataDiagram.puml
  docs/diagrams/class/Data_diagram.png
  docs/diagrams/class/Main.png
  docs/diagrams/class/Main.puml
  docs/diagrams/class/ParserDiagram.png
  docs/diagrams/class/ParserDiagram.puml
  docs/diagrams/class/Parser_diagram.png
Labels: type.Task

#67 Fixes some documentation issues
  docs/DeveloperGuide.md
  docs/diagrams/sequence/Main.puml
Labels: type.Task, priority.Medium

#68 Adds solve attempt logging
  .gitignore
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/logging/BaseLogger.java
  src/main/java/mindexpander/logging/LogsManager.java
  src/main/java/mindexpander/logging/SolveAttemptLogger.java
  src/main/java/mindexpander/storage/StorageFile.java
  src/main/java/mindexpander/ui/TextUi.java
Labels: type.Task, priority.High

#98 Adds True False question type
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/class/DataDiagram.puml
  docs/diagrams/class/StorageFileDiagram.png
  docs/diagrams/class/StorageFileDiagram.puml
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/EditCommand.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/data/question/QuestionType.java
  src/main/java/mindexpander/data/question/TrueFalse.java
  src/main/java/mindexpander/parser/Parser.java
  src/main/java/mindexpander/storage/StorageFile.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#99 Fix bugs from ped
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/sequence/Find.png
  docs/diagrams/sequence/Find.puml
  docs/diagrams/sequence/List.png
  docs/diagrams/sequence/List.puml
  src/main/java/mindexpander/commands/FindCommand.java
  src/main/java/mindexpander/common/Messages.java
  src/main/java/mindexpander/data/question/MultipleChoice.java
  src/main/java/mindexpander/parser/Parser.java
  src/main/java/mindexpander/ui/TextUi.java
  src/test/java/mindexpander/tests/FindCommandTest.java
  src/test/java/mindexpander/tests/ListCommandTest.java
Labels: type.Bug

#100 Branch improve code quality
  docs/UserGuide.md
  docs/team/flaaaash.md
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/EditCommand.java
  src/main/java/mindexpander/commands/Multistep.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/data/question/FillInTheBlanks.java
  src/main/java/mindexpander/data/question/MultipleChoice.java
  src/main/java/mindexpander/data/question/Question.java
  src/main/java/mindexpander/data/question/QuestionType.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/AddCommandTest.java
  src/test/java/mindexpander/tests/EditCommandTest.java
  src/test/java/mindexpander/tests/SolveCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Enhancement, priority.High

#101 Fixes PED issues
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/sequence/Main.png
  docs/diagrams/sequence/Main.puml
  docs/team/Jensenkuok.md
  docs/team/lwenyi1.md
Labels: type.Bug, priority.Medium

#103 Implement error logging and show command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/sequence/Find.png
  docs/diagrams/sequence/Find.puml
  docs/diagrams/sequence/List.png
  docs/diagrams/sequence/List.puml
  docs/diagrams/sequence/Show.png
  docs/diagrams/sequence/Show.puml
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/CommandResult.java
  src/main/java/mindexpander/commands/FindCommand.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/commands/ListCommand.java
  src/main/java/mindexpander/commands/ShowCommand.java
  src/main/java/mindexpander/common/Messages.java
  src/main/java/mindexpander/logging/ErrorLogger.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/FindCommandTest.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  src/test/java/mindexpander/tests/ListCommandTest.java
  src/test/java/mindexpander/tests/ShowCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, type.Task, priority.Medium

#104 Branch undo redo
  src/main/java/mindexpander/Main.java
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/Command.java
  src/main/java/mindexpander/commands/DeleteCommand.java
  src/main/java/mindexpander/commands/EditCommand.java
  src/main/java/mindexpander/commands/Multistep.java
  src/main/java/mindexpander/commands/RedoCommand.java
  src/main/java/mindexpander/commands/SolveCommand.java
  src/main/java/mindexpander/commands/Tracable.java
  src/main/java/mindexpander/commands/UndoCommand.java
  src/main/java/mindexpander/data/CommandHistory.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/AddCommandTest.java
  src/test/java/mindexpander/tests/DeleteCommandTest.java
  src/test/java/mindexpander/tests/EditCommandTest.java
  src/test/java/mindexpander/tests/FindCommandTest.java
  src/test/java/mindexpander/tests/ListCommandTest.java
  src/test/java/mindexpander/tests/ShowCommandTest.java
  src/test/java/mindexpander/tests/SolveCommandTest.java
Labels: severity.Low, type.Story, priority.Medium

#105 Adds Questions logger, adds input validation for reserved delimiters, adds ClearCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/mindexpander/commands/AddCommand.java
  src/main/java/mindexpander/commands/ClearCommand.java
  src/main/java/mindexpander/commands/DeleteCommand.java
  src/main/java/mindexpander/commands/EditCommand.java
  src/main/java/mindexpander/commands/HelpCommand.java
  src/main/java/mindexpander/common/InputValidator.java
  src/main/java/mindexpander/data/QuestionBank.java
  src/main/java/mindexpander/logging/QuestionLogger.java
  src/main/java/mindexpander/parser/Parser.java
  src/test/java/mindexpander/tests/ClearCommandTest.java
  src/test/java/mindexpander/tests/DeleteCommandTest.java
  src/test/java/mindexpander/tests/HelpCommandTest.java
  src/test/java/mindexpander/tests/InputValidatorTest.java
  src/test/java/mindexpander/tests/StorageFileTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium

#108 Branch fix solve logger
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/mindexpander/logging/SolveAttemptLogger.java
Labels: severity.High, type.Bug

#114 Fixed bug for edit after add will cause error in undo.
  src/main/java/mindexpander/commands/AddCommand.java
Labels: severity.High, priority.High
